version: '3.5'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    user: '0:0'
    container_name: northwind
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password01.
      MSSQL_PID: Express